"""change stock

Revision ID: 084d1e767fa9
Revises: 
Create Date: 2018-06-10 20:13:48.191311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084d1e767fa9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=140), nullable=True),
    sa.Column('tipo', sa.String(length=140), nullable=True),
    sa.Column('cor', sa.String(length=140), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calha_timestamp'), 'calha', ['timestamp'], unique=False)
    op.create_table('melamina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espessura', sa.String(length=140), nullable=True),
    sa.Column('cor', sa.String(length=140), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_melamina_timestamp'), 'melamina', ['timestamp'], unique=False)
    op.create_table('modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=140), nullable=True),
    sa.Column('receita', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelo_timestamp'), 'modelo', ['timestamp'], unique=False)
    op.create_table('perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=140), nullable=True),
    sa.Column('tipo', sa.String(length=140), nullable=True),
    sa.Column('cor', sa.String(length=140), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfil_timestamp'), 'perfil', ['timestamp'], unique=False)
    op.create_table('rodizio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=140), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rodizio_timestamp'), 'rodizio', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('vidro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=140), nullable=True),
    sa.Column('cor', sa.String(length=140), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vidro_timestamp'), 'vidro', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vidro_timestamp'), table_name='vidro')
    op.drop_table('vidro')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_rodizio_timestamp'), table_name='rodizio')
    op.drop_table('rodizio')
    op.drop_index(op.f('ix_perfil_timestamp'), table_name='perfil')
    op.drop_table('perfil')
    op.drop_index(op.f('ix_modelo_timestamp'), table_name='modelo')
    op.drop_table('modelo')
    op.drop_index(op.f('ix_melamina_timestamp'), table_name='melamina')
    op.drop_table('melamina')
    op.drop_index(op.f('ix_calha_timestamp'), table_name='calha')
    op.drop_table('calha')
    # ### end Alembic commands ###
